allowBuilds:
  esbuild: true
minimumReleaseAgeExclude:
  - '@kolkrabbi/kol-component@0.1.1 || 0.5.0 || 0.6.0'
  - '@kolkrabbi/kol-framework@0.1.1'
  - '@kolkrabbi/kol-icons@0.4.0 || 0.5.0'
  - '@kolkrabbi/kol-theme@0.1.1 || 0.5.0 || 0.6.0'
